In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\prave\OneDrive\Desktop\ai-engineer-journey\csv_files\Online_Retail.csv",encoding="latin1")

In [5]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

**1. Understanding How big this dataset**

In [9]:
print(f"Number of rows in dataset is: {df.shape[0]}")
print(f"Number of columns in dataset is: {df.shape[1]}")
print(f"Total number of data points in this dataset is: {df.shape[0] * df.shape[1]}")

Number of rows in dataset is: 541909
Number of columns in dataset is: 8
Total number of data points in this dataset is: 4335272

**2. Understanding each columns**

In [11]:
for i,column in enumerate(df.columns):
    print(f"{i+1}. {column}")

1. InvoiceNo
2. StockCode
3. Description
4. Quantity
5. InvoiceDate
6. UnitPrice
7. CustomerID
8. Country

**3. See the actual data**

In [16]:
print("see the first 5 rows\n")
df.head(5)

see the first 5 rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [17]:
print("see the last 5 rows\n")
df.tail(5)

see the last 5 rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,09-12-2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680.0,France

In [19]:
print("see sample of 5 rows\n")
df.sample(5)

see sample of 5 rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
86312,543544,21916,SET 12 RETRO WHITE CHALK STICKS,1,09-02-2011 15:39,0.42,NaN,United Kingdom
156044,550057,21280,VINTAGE KITCHEN PRINT VEGETABLES,1,14-04-2011 12:01,2.55,14606.0,United Kingdom
443652,574707,23356,LOVE HOT WATER BOTTLE,1,06-11-2011 14:08,5.95,17107.0,United Kingdom
482262,577438,22139,RETROSPOT TEA SET CERAMIC 11 PC,1,20-11-2011 11:09,4.95,18118.0,United Kingdom
497202,578349,23480,MINI LIGHTS WOODLAND MUSHROOMS,4,24-11-2011 09:50,3.75,14539.0,United Kingdom

**3. Understanding each column Datatype**

In [29]:
df.dtypes
print()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [30]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000